version: '3'
services:
  client:
    image: team34lyfe/shoppingcart-client:latest
    ports:
      - 1234:1234
  server:
    image: team34lyfe/shoppingcart-server:latest
    ports:
      - 5001:5001
    environment:
      - DB=${DB}